// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateCompra(arg1:main.Compra):Promise<main.CompraResponse>;

export function CreateCustomer(arg1:main.Customer):Promise<main.CustomerResponse>;

export function CreateProduct(arg1:main.Product):Promise<main.ProductResponse>;

export function CreateUser(arg1:main.User):Promise<main.CreateUserResponse>;

export function CreateVenda(arg1:main.Venda):Promise<main.VendaResponse>;

export function DeleteCustomer(arg1:number):Promise<boolean>;

export function DeleteProduct(arg1:number):Promise<boolean>;

export function DeleteUser(arg1:string):Promise<boolean>;

export function GetCompras():Promise<Array<main.Compra>>;

export function GetCustomers():Promise<Array<main.Customer>>;

export function GetProducts():Promise<Array<main.Product>>;

export function GetUsers():Promise<Array<main.User>>;

export function GetVendas():Promise<Array<main.Venda>>;

export function Login(arg1:string,arg2:string):Promise<main.LoginResponse>;

export function UpdateCustomer(arg1:number,arg2:main.Customer):Promise<main.CustomerResponse>;

export function UpdateProduct(arg1:number,arg2:main.Product):Promise<main.ProductResponse>;

export function UpdateUser(arg1:string,arg2:main.User):Promise<main.CreateUserResponse>;
