// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCompra(arg1) {
  return window['go']['main']['App']['CreateCompra'](arg1);
}

export function CreateCustomer(arg1) {
  return window['go']['main']['App']['CreateCustomer'](arg1);
}

export function CreateProduct(arg1) {
  return window['go']['main']['App']['CreateProduct'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function CreateVenda(arg1) {
  return window['go']['main']['App']['CreateVenda'](arg1);
}

export function DeleteCustomer(arg1) {
  return window['go']['main']['App']['DeleteCustomer'](arg1);
}

export function DeleteProduct(arg1) {
  return window['go']['main']['App']['DeleteProduct'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function GetCompras() {
  return window['go']['main']['App']['GetCompras']();
}

export function GetCustomers() {
  return window['go']['main']['App']['GetCustomers']();
}

export function GetProducts() {
  return window['go']['main']['App']['GetProducts']();
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function GetVendas() {
  return window['go']['main']['App']['GetVendas']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}
